device: cuda:1

run_dir: ???

ckpt: last

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 8
  num_workers: 8

examples: true

defaults:
  - data: babel-classifier
  - model: classifier
  # - trainer
  - defaults
  - _self_

data:
  preload: false